
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'rental_analytics'
version: '1.0.0'
profile: 'rental_analytics'

model-paths: ["models"]
seed-paths: ["seeds"]

models:
  rental_analytics:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table

seeds:
  rental_analytics:
    raw:
      listings:
        +column_types:
          PRICE: varchar
      calendar:
        +column_types:
          AVAILABLE: varchar
          RESERVATION_ID: varchar
          PRICE: varchar
